title: "OrcsaVik's Tech Blog"
description: "A clean, responsive Jekyll blog with card-based design and dark aesthetic"
baseurl: ""          # Leave empty for username.github.io; use "/repo-name" for project pages
url: "https://orcsavik.github.io"

# No external theme for complete control
theme: null
markdown: kramdown
highlighter: rouge

# Site author
author:
  name: "OrcsaVik"
