title: "OrcsaVik Blog"
description: "一个炫酷的 GitHub Pages 静态博客"
baseurl: "" # username.github.io 时为空
url: "https://orcsaVik.github.io"

theme: null
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 文章相关配置
paginate: 10
paginate_path: "/page:num/"

# 站点元数据
author:
  name: OrcsaVik
  email: your_email@example.com
