# _config.yml
title: 我的技术博客
email: your-email@example.com
description: 记录学习与成长
github_username: zhangsan
theme: jekyll-theme-cayman  # 可选其他官方主题

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
